"""Documentation generator for projects."""

from pathlib import Path
from typing import Dict, Any
from datetime import datetime


class DocumentationGenerator:
    """Generate project documentation."""

    def __init__(self, project_dir: Path):
        """Initialize documentation generator.

        Args:
            project_dir: Path to project directory
        """
        self.project_dir = project_dir

    def generate_readme(
        self,
        intent: Dict[str, Any],
        winner: Dict[str, Any],
        comparison: Dict[str, Any]
    ):
        """Generate README.md for the project.

        Args:
            intent: Parsed intent
            winner: Winner dictionary
            comparison: Comparison results
        """
        target_variable = intent.get("target_variable", "target")
        task_type = intent.get("task_type", "binary_classification")
        model_name = winner.get("model_name", "model")
        threshold = winner.get("threshold", 0.5)

        business_impact = comparison.get("business_impact", {})
        financial_impact = comparison.get("financial_impact", {})

        readme = f"""# ML Project - {target_variable} Prediction

Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Overview

This project implements a machine learning pipeline for predicting **{target_variable}** using a **{task_type}** approach.

## Model Information

- **Model**: {model_name}
- **Strategy**: {winner.get('strategy_name', 'unknown')}
- **Threshold**: {threshold}
- **Task Type**: {task_type}

## Performance

### Business Impact

- **True Positives**: {business_impact.get('true_positives', 0)}
- **False Positives**: {business_impact.get('false_positives', 0)}
- **False Negatives**: {business_impact.get('false_negatives', 0)}
- **Total Actions**: {business_impact.get('total_actions', 0)}

### Financial Impact

- **Potential Value**: ${financial_impact.get('potential_value', 0):,.0f}
- **Total Cost**: ${financial_impact.get('total_cost', 0):,.0f}
- **Net Value**: ${financial_impact.get('net_value', 0):,.0f}
- **ROI**: {financial_impact.get('roi', 0):.1f}x

## Project Structure

```
.
├── data/
│   ├── processed/     # Processed data files
│   └── raw/          # Raw data files
├── models/            # Saved models and pipelines
├── src/
│   ├── preprocessing.py  # Data preprocessing
│   ├── train.py          # Model training
│   └── predict.py        # Prediction script
└── requirements.txt   # Python dependencies
```

## Usage

### 1. Install Dependencies

```bash
pip install -r requirements.txt
```

### 2. Preprocess Data

```python
from src.preprocessing import preprocess_data

processed_data = preprocess_data("data/raw/data.csv", "models/preprocessing.pkl")
```

### 3. Make Predictions

```python
from src.predict import predict

results = predict("data/raw/new_data.csv", threshold={threshold})
results.to_csv("data/processed/predictions.csv", index=False)
```

## Model Details

The model was trained using the following approach:
- **Preprocessing Strategy**: {winner.get('strategy_name', 'unknown')}
- **Model Type**: {model_name}
- **Optimization Metric**: {intent.get('business_context', {}).get('priority_metric', 'N/A')}

## Notes

- The model and preprocessing pipeline are saved in the `models/` directory
- Adjust the threshold in `predict.py` to optimize for different business goals
- For classification tasks, threshold of {threshold} was found to be optimal

## Generated By

Intent-Driven AutoML Platform
"""

        output_path = self.project_dir / "README.md"
        output_path.write_text(readme, encoding="utf-8")
